<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>false</InvariantGlobalization>
      <UserSecretsId>43b66677-f99c-4be4-95a9-a046f5adf471</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Audora.Application\Audora.Application.csproj" />
      <ProjectReference Include="..\Audora.Contracts\Audora.Contracts.csproj" />
      <ProjectReference Include="..\Audora.Infrastructure\Audora.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4" />
    </ItemGroup>

</Project>
